// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0LAlMfO94hIwxOHX8_eY71TCVbRO3Row',
    appId: '1:501677723437:web:4e4506d6505b3fd1eacda4',
    messagingSenderId: '501677723437',
    projectId: 'tatlisozluk-8f8c6',
    authDomain: 'tatlisozluk-8f8c6.firebaseapp.com',
    storageBucket: 'tatlisozluk-8f8c6.firebasestorage.app',
    measurementId: 'G-EYFHBLMS4X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoxEfK2ygVFcf2HMsDSsnEei0w1DvR5Vc',
    appId: '1:501677723437:android:fa0b7e2c046fc89aeacda4',
    messagingSenderId: '501677723437',
    projectId: 'tatlisozluk-8f8c6',
    storageBucket: 'tatlisozluk-8f8c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp4HNkF4pSTLaRNu77sckIy0uKezCRxk4',
    appId: '1:501677723437:ios:e1ee3a60d341cb27eacda4',
    messagingSenderId: '501677723437',
    projectId: 'tatlisozluk-8f8c6',
    storageBucket: 'tatlisozluk-8f8c6.firebasestorage.app',
    iosBundleId: 'com.example.tatliSozluk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp4HNkF4pSTLaRNu77sckIy0uKezCRxk4',
    appId: '1:501677723437:ios:e1ee3a60d341cb27eacda4',
    messagingSenderId: '501677723437',
    projectId: 'tatlisozluk-8f8c6',
    storageBucket: 'tatlisozluk-8f8c6.firebasestorage.app',
    iosBundleId: 'com.example.tatliSozluk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0LAlMfO94hIwxOHX8_eY71TCVbRO3Row',
    appId: '1:501677723437:web:4a9b1a0806689a89eacda4',
    messagingSenderId: '501677723437',
    projectId: 'tatlisozluk-8f8c6',
    authDomain: 'tatlisozluk-8f8c6.firebaseapp.com',
    storageBucket: 'tatlisozluk-8f8c6.firebasestorage.app',
    measurementId: 'G-TZJR2B7RPG',
  );
}
